DROP TABLE IF EXISTS `balance_sheet`;
CREATE TABLE `balance_sheet` (
  `balance_sheet_id` int(11) NOT NULL AUTO_INCREMENT,
  `years` varchar(4) NOT NULL,
  `month` varchar(2) NOT NULL,
  `company_id` int(11) NOT NULL COMMENT '分公司ID',
  `monetary_resources` decimal(10,2) DEFAULT '0.00' COMMENT '货币资金',
  `short_term_investment` decimal(10,2) DEFAULT '0.00' COMMENT '短期投资',
  `dividends_receivable` decimal(10,2) DEFAULT '0.00' COMMENT '应收股利',
  `accounts_receivable` decimal(10,2) DEFAULT '0.00' COMMENT '应收帐款',
  `other_receivables` decimal(10,2) DEFAULT '0.00' COMMENT '其他应收款',
  `advance_payment` decimal(10,2) DEFAULT '0.00' COMMENT '预付账款',
  `deferred_expenses` decimal(10,2) DEFAULT '0.00' COMMENT '待摊费用',
  `net_loss_of_current_assets_to_be_processed` decimal(10,2) DEFAULT '0.00' COMMENT '待处理流动资产净损失',
  `investments_in_longterm_bonds_maturing_in_one_year` decimal(10,2) DEFAULT '0.00' COMMENT '一年内到期的长期债券投资',
  `other_current_assets` decimal(10,2) DEFAULT '0.00' COMMENT '其他流动资产',
  `total_current_assets` decimal(10,2) DEFAULT '0.00' COMMENT '流动资产合计',
  `long_term_equity_investment` decimal(10,2) DEFAULT '0.00' COMMENT '长期股权投资',
  `long_term_debt_investment` decimal(10,2) DEFAULT '0.00' COMMENT '长期债权投资',
  `long_term_investment_impairment_provision` decimal(10,2) DEFAULT '0.00' COMMENT '长期投资减值准备',
  `net_long_term_investment` decimal(10,2) DEFAULT '0.00' COMMENT '长期投资净额',
  `original_value_of_fixed_assets` decimal(10,2) DEFAULT '0.00' COMMENT '固定资产原价',
  `accumulated_depreciation` decimal(10,2) DEFAULT '0.00' COMMENT '累计折旧',
  `fixed_assetsnet_value` decimal(10,2) DEFAULT '0.00' COMMENT '固定资产净值',
  `Provision_for_impairment_of_fixed_assets` decimal(10,2) DEFAULT '0.00' COMMENT '固定资产减值准备',
  `net_fixed_assets` decimal(10,2) DEFAULT '0.00' COMMENT '固定资产净额',
  `immaterial_assets` decimal(10,2) DEFAULT '0.00' COMMENT '无形资产',
  `provision_for_impairment_of_intangible_assets` decimal(10,2) DEFAULT '0.00' COMMENT '无形资产减值准备',
  `net_intangible_assets` decimal(10,2) DEFAULT '0.00' COMMENT '无形资产净额',
  `total_noncurrent_assets` decimal(10,2) DEFAULT '0.00' COMMENT '非流动资产合计',
  `total_assets` decimal(10,2) DEFAULT '0.00' COMMENT '资产总计',
  `overnight_money` decimal(10,2) DEFAULT '0.00' COMMENT '短期借款',
  `payable_in_account` decimal(10,2) DEFAULT '0.00' COMMENT '应付账款',
  `deposit_received` decimal(10,2) DEFAULT '0.00' COMMENT '预收账款',
  `pay_payable_to_staff_and_workers` decimal(10,2) DEFAULT '0.00' COMMENT '应付职工薪酬',
  `dividends_payable` decimal(10,2) DEFAULT '0.00' COMMENT '应付股利',
  `due_taxes_and_fees` decimal(10,2) DEFAULT '0.00' COMMENT '应交税费',
  `other_accounts_payable` decimal(10,2) DEFAULT '0.00' COMMENT '其他应交款',
  `accounts_payable_others` decimal(10,2) DEFAULT '0.00' COMMENT '其他应付款',
  `longterm_liabilities_due_within_one_year` decimal(10,2) DEFAULT '0.00' COMMENT '一年内到期的长期负债',
  `other_current_liabilities` decimal(10,2) DEFAULT '0.00' COMMENT '其他流动负债',
  `total_current_liabilities` decimal(10,2) DEFAULT '0.00' COMMENT '流动负债合计',
  `money_borrowed_for_long_term` decimal(10,2) DEFAULT '0.00' COMMENT '长期借款',
  `bond_payable` decimal(10,2) DEFAULT '0.00' COMMENT '应付债券',
  `long_term_accounts_payable` decimal(10,2) DEFAULT '0.00' COMMENT '长期应付款',
  `account_payable_special_funds` decimal(10,2) DEFAULT '0.00' COMMENT '专项应付款',
  `other_long_term_liabilities` decimal(10,2) DEFAULT '0.00' COMMENT '其他长期负债',
  `total_long_term_liabilities` decimal(10,2) DEFAULT '0.00' COMMENT '长期负债合计',
  `total_liabilities` decimal(10,2) DEFAULT '0.00' COMMENT '负债合计',
  `paid_in_capital_or_share_capital` decimal(10,2) DEFAULT '0.00' COMMENT '实收资本(或股本)',
  `capital_reserve` decimal(10,2) DEFAULT '0.00' COMMENT '资本公积',
  `earned_surplus` decimal(10,2) DEFAULT '0.00' COMMENT '盈余公积',
  `undistributed_profit` decimal(10,2) DEFAULT '0.00' COMMENT '未分配利润',
  `foreign_currency_statement_translation_difference` decimal(10,2) DEFAULT '0.00' COMMENT '外币报表折算差额',
  `total_owners_equity_or_shareholders_equity` decimal(10,2) DEFAULT '0.00' COMMENT '所有者权益(或股东权益)合计',
  `total_liabilities_and_owners_equity_or_shareholders_equity` decimal(10,2) DEFAULT '0.00' COMMENT ' 负债及所有者权益(或股东权益)总计',
  `create_time` int(11) DEFAULT NULL,
  `update_time` int(11) DEFAULT NULL,
  `create_user_id` int(11) DEFAULT NULL,
  `update_user_id` int(11) DEFAULT NULL,
  `status` tinyint(2) DEFAULT '1',
  PRIMARY KEY (`balance_sheet_id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='资产负债表';





