/*
 Navicat Premium Data Transfer

 Source Server         : 192.168.11.122
 Source Server Type    : MySQL
 Source Server Version : 100109
 Source Host           : 192.168.11.122:3306
 Source Schema         : erp

 Target Server Type    : MySQL
 Target Server Version : 100109
 File Encoding         : 65001

 Date: 22/07/2019 16:17:29
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for time_zone
-- ----------------------------
DROP TABLE IF EXISTS `time_zone`;
CREATE TABLE `time_zone`  (
  `time_zone_id` int(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_german2_ci DEFAULT NULL,
  PRIMARY KEY (`time_zone_id`) USING BTREE
) ENGINE = InnoDB AUTO_INCREMENT = 389 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Compact;

-- ----------------------------
-- Records of time_zone
-- ----------------------------
INSERT INTO `time_zone` VALUES (1, '(UTC +1) Alpha Time Zone');
INSERT INTO `time_zone` VALUES (2, '(UTC +10:30) Australian Central Daylight Time ');
INSERT INTO `time_zone` VALUES (3, '(UTC +10:30) CDT – Central Daylight Time');
INSERT INTO `time_zone` VALUES (4, '(UTC +10:30) CDST – Central Daylight Savings Time');
INSERT INTO `time_zone` VALUES (5, '(UTC +9:30) Australian Central Standard Time ');
INSERT INTO `time_zone` VALUES (6, '(UTC +9:30) CST – Central Standard Time');
INSERT INTO `time_zone` VALUES (7, '(UTC -5) Acre Time');
INSERT INTO `time_zone` VALUES (8, '(UTC +9:30 / +10:30) Australian Central Time');
INSERT INTO `time_zone` VALUES (9, '(UTC +8:45) Australian Central Western Standard Time');
INSERT INTO `time_zone` VALUES (10, '(UTC +4) Arabia Daylight Time ');
INSERT INTO `time_zone` VALUES (11, '(UTC +4) AST – Arabia Summer Time');
INSERT INTO `time_zone` VALUES (12, '(UTC -3) Atlantic Daylight Time ');
INSERT INTO `time_zone` VALUES (13, '(UTC -3) ADST – Atlantic Daylight Saving Time');
INSERT INTO `time_zone` VALUES (14, '(UTC -3) AST – Atlantic Summer Time ');
INSERT INTO `time_zone` VALUES (15, '(UTC -3) HAA – Heure Avancée de l\'Atlantique (French)');
INSERT INTO `time_zone` VALUES (16, '(UTC +11) Australian Eastern Daylight Time ');
INSERT INTO `time_zone` VALUES (17, '(UTC +11) EDT – Eastern Daylight Time');
INSERT INTO `time_zone` VALUES (18, '(UTC +11) EDST – Eastern Daylight Saving Time');
INSERT INTO `time_zone` VALUES (19, '(UTC +10) Australian Eastern Standard Time ');
INSERT INTO `time_zone` VALUES (20, '(UTC +10) EST – Eastern Standard Time');
INSERT INTO `time_zone` VALUES (21, '(UTC +10) AET – Australian Eastern Time');
INSERT INTO `time_zone` VALUES (22, '(UTC +10:00 / +11:00) Australian Eastern Time');
INSERT INTO `time_zone` VALUES (23, '(UTC +4:30) Afghanistan Time');
INSERT INTO `time_zone` VALUES (24, '(UTC -8) Alaska Daylight Time ');
INSERT INTO `time_zone` VALUES (25, '(UTC -8) ADST – Alaska Daylight Saving Time');
INSERT INTO `time_zone` VALUES (26, '(UTC -9) Alaska Standard Time ');
INSERT INTO `time_zone` VALUES (27, '(UTC -9) AT – Alaska Time');
INSERT INTO `time_zone` VALUES (28, '(UTC +6) Alma-Ata Time');
INSERT INTO `time_zone` VALUES (29, '(UTC -3) Amazon Summer Time');
INSERT INTO `time_zone` VALUES (30, '(UTC +5) Armenia Summer Time ');
INSERT INTO `time_zone` VALUES (31, '(UTC +5) AMDT – Armenia Daylight Time');
INSERT INTO `time_zone` VALUES (32, '(UTC -4) Amazon Time');
INSERT INTO `time_zone` VALUES (33, '(UTC +4) Armenia Time');
INSERT INTO `time_zone` VALUES (34, '(UTC +12) Anadyr Summer Time');
INSERT INTO `time_zone` VALUES (35, '(UTC +12) Anadyr Time');
INSERT INTO `time_zone` VALUES (36, '(UTC +5) Aqtobe Time');
INSERT INTO `time_zone` VALUES (37, '(UTC -3) Argentina Time');
INSERT INTO `time_zone` VALUES (39, '(UTC +3) Arabia Standard Time ');
INSERT INTO `time_zone` VALUES (40, '(UTC +3) AST – Arabic Standard Time');
INSERT INTO `time_zone` VALUES (41, '(UTC +3) AST – Al Manamah Standard Time');
INSERT INTO `time_zone` VALUES (42, '(UTC -4) Atlantic Standard Time ');
INSERT INTO `time_zone` VALUES (43, '(UTC -4) AT – Atlantic Time ');
INSERT INTO `time_zone` VALUES (44, '(UTC -4) AST – Tiempo Estándar del Atlántico (Spanish)');
INSERT INTO `time_zone` VALUES (45, '(UTC -4) HNA – Heure Normale de l\'Atlantique (French)');
INSERT INTO `time_zone` VALUES (46, '(UTC -4:00 / -3:00) Atlantic Time');
INSERT INTO `time_zone` VALUES (48, '(UTC +9) Australian Western Daylight Time ');
INSERT INTO `time_zone` VALUES (49, '(UTC +9) WDT – Western Daylight Time');
INSERT INTO `time_zone` VALUES (50, '(UTC +9) WST – Western Summer Time');
INSERT INTO `time_zone` VALUES (51, '(UTC +8) Australian Western Standard Time ');
INSERT INTO `time_zone` VALUES (52, '(UTC +8) WST – Western Standard Time');
INSERT INTO `time_zone` VALUES (53, '(UTC +8) WAT – Western Australia Time');
INSERT INTO `time_zone` VALUES (54, '(UTC +0) Azores Summer Time ');
INSERT INTO `time_zone` VALUES (55, '(UTC +0) AZODT – Azores Daylight Time');
INSERT INTO `time_zone` VALUES (56, '(UTC -1) Azores Time ');
INSERT INTO `time_zone` VALUES (57, '(UTC -1) AZOST – Azores Standard Time');
INSERT INTO `time_zone` VALUES (58, '(UTC +5) Azerbaijan Summer Time');
INSERT INTO `time_zone` VALUES (59, '(UTC +4) Azerbaijan Time');
INSERT INTO `time_zone` VALUES (60, '(UTC -12) Anywhere on Earth');
INSERT INTO `time_zone` VALUES (61, '(UTC +2) Bravo Time Zone');
INSERT INTO `time_zone` VALUES (62, '(UTC +8) Brunei Darussalam Time ');
INSERT INTO `time_zone` VALUES (63, '(UTC +8) BDT – Brunei Time');
INSERT INTO `time_zone` VALUES (64, '(UTC -4) Bolivia Time');
INSERT INTO `time_zone` VALUES (65, '(UTC -2) Brasília Summer Time ');
INSERT INTO `time_zone` VALUES (66, '(UTC -2) BST – Brazil Summer Time');
INSERT INTO `time_zone` VALUES (67, '(UTC -2) BST – Brazilian Summer Time');
INSERT INTO `time_zone` VALUES (68, '(UTC -3) Brasília Time ');
INSERT INTO `time_zone` VALUES (69, '(UTC -3) BT – Brazil Time');
INSERT INTO `time_zone` VALUES (70, '(UTC -3) BT – Brazilian Time');
INSERT INTO `time_zone` VALUES (71, '(UTC +6) Bangladesh Standard Time');
INSERT INTO `time_zone` VALUES (72, '(UTC +11) Bougainville Standard Time');
INSERT INTO `time_zone` VALUES (73, '(UTC +1) British Summer Time ');
INSERT INTO `time_zone` VALUES (74, '(UTC +1) BDT – British Daylight Time');
INSERT INTO `time_zone` VALUES (75, '(UTC +1) BDST – British Daylight Saving Time');
INSERT INTO `time_zone` VALUES (76, '(UTC +6) Bhutan Time');
INSERT INTO `time_zone` VALUES (77, '(UTC +3) Charlie Time Zone');
INSERT INTO `time_zone` VALUES (78, '(UTC +8) Casey Time');
INSERT INTO `time_zone` VALUES (79, '(UTC +2) Central Africa Time');
INSERT INTO `time_zone` VALUES (80, '(UTC +6:30) Cocos Islands Time');
INSERT INTO `time_zone` VALUES (81, '(UTC -5) Central Daylight Time ');
INSERT INTO `time_zone` VALUES (82, '(UTC -5) CDST – Central Daylight Saving Time');
INSERT INTO `time_zone` VALUES (83, '(UTC -5) NACDT – North American Central Daylight Time ');
INSERT INTO `time_zone` VALUES (84, '(UTC -5) HAC – Heure Avancée du Centre (French)');
INSERT INTO `time_zone` VALUES (85, '(UTC -4) Cuba Daylight Time');
INSERT INTO `time_zone` VALUES (86, '(UTC +2) Central European Summer Time ');
INSERT INTO `time_zone` VALUES (87, '(UTC +2) CEDT – Central European Daylight Time');
INSERT INTO `time_zone` VALUES (88, '(UTC +2) ECST – European Central Summer Time ');
INSERT INTO `time_zone` VALUES (89, '(UTC +2) MESZ – Mitteleuropäische Sommerzeit (German)');
INSERT INTO `time_zone` VALUES (90, '(UTC +1) Central European Time ');
INSERT INTO `time_zone` VALUES (91, '(UTC +1) ECT – European Central Time');
INSERT INTO `time_zone` VALUES (92, '(UTC +1) CET – Central Europe Time ');
INSERT INTO `time_zone` VALUES (93, '(UTC +1) MEZ – Mitteleuropäische Zeit (German)');
INSERT INTO `time_zone` VALUES (94, '(UTC +13:45) Chatham Island Daylight Time ');
INSERT INTO `time_zone` VALUES (95, '(UTC +13:45) CDT – Chatham Daylight Time');
INSERT INTO `time_zone` VALUES (96, '(UTC +12:45) Chatham Island Standard Time');
INSERT INTO `time_zone` VALUES (97, '(UTC +9) Choibalsan Summer Time ');
INSERT INTO `time_zone` VALUES (98, '(UTC +9) CHODT – Choibalsan Daylight Time');
INSERT INTO `time_zone` VALUES (99, '(UTC +9) CHODST – Choibalsan Daylight Saving Time');
INSERT INTO `time_zone` VALUES (100, '(UTC +8) Choibalsan Time');
INSERT INTO `time_zone` VALUES (101, '(UTC +10) Chuuk Time');
INSERT INTO `time_zone` VALUES (102, '(UTC -4) Cayman Islands Daylight Saving Time');
INSERT INTO `time_zone` VALUES (103, '(UTC -5) Cayman Islands Standard Time ');
INSERT INTO `time_zone` VALUES (104, '(UTC -5) CIT – Cayman Islands Time');
INSERT INTO `time_zone` VALUES (105, '(UTC -10) Cook Island Time');
INSERT INTO `time_zone` VALUES (106, '(UTC -3) Chile Summer Time ');
INSERT INTO `time_zone` VALUES (107, '(UTC -3) CLDT – Chile Daylight Time');
INSERT INTO `time_zone` VALUES (108, '(UTC -4) Chile Standard Time ');
INSERT INTO `time_zone` VALUES (109, '(UTC -4) CT – Chile Time');
INSERT INTO `time_zone` VALUES (110, '(UTC -4) CLST – Chile Standard Time');
INSERT INTO `time_zone` VALUES (111, '(UTC -5) Colombia Time');
INSERT INTO `time_zone` VALUES (112, '(UTC -6) Central Standard Time ');
INSERT INTO `time_zone` VALUES (113, '(UTC -6) CT – Central Time');
INSERT INTO `time_zone` VALUES (114, '(UTC -6) NACST – North American Central Standard Time ');
INSERT INTO `time_zone` VALUES (115, '(UTC -6) CST – Tiempo Central Estándar (Spanish)');
INSERT INTO `time_zone` VALUES (116, '(UTC -6) HNC – Heure Normale du Centre (French)');
INSERT INTO `time_zone` VALUES (117, '(UTC +8) China Standard Time');
INSERT INTO `time_zone` VALUES (118, '(UTC -5) Cuba Standard Time');
INSERT INTO `time_zone` VALUES (119, '(UTC -6:00 / -5:00) Central Time');
INSERT INTO `time_zone` VALUES (120, '(UTC -1) Cape Verde Time');
INSERT INTO `time_zone` VALUES (121, '(UTC +7) Christmas Island Time');
INSERT INTO `time_zone` VALUES (122, '(UTC +10) Chamorro Standard Time ');
INSERT INTO `time_zone` VALUES (123, '(UTC +10) GST – Guam Standard Time');
INSERT INTO `time_zone` VALUES (124, '(UTC +4) Delta Time Zone');
INSERT INTO `time_zone` VALUES (125, '(UTC +7) Davis Time');
INSERT INTO `time_zone` VALUES (126, '(UTC +10) Dumont-d\'Urville Time');
INSERT INTO `time_zone` VALUES (127, '(UTC +5) Echo Time Zone');
INSERT INTO `time_zone` VALUES (128, '(UTC -5) Easter Island Summer Time ');
INSERT INTO `time_zone` VALUES (129, '(UTC -5) EADT – Easter Island Daylight Time');
INSERT INTO `time_zone` VALUES (130, '(UTC -6) Easter Island Standard Time');
INSERT INTO `time_zone` VALUES (131, '(UTC +3) Eastern Africa Time ');
INSERT INTO `time_zone` VALUES (132, '(UTC +3) EAT – East Africa Time');
INSERT INTO `time_zone` VALUES (133, '(UTC -5) Ecuador Time');
INSERT INTO `time_zone` VALUES (134, '(UTC -4) Eastern Daylight Time ');
INSERT INTO `time_zone` VALUES (135, '(UTC -4) EDST – Eastern Daylight Savings Time');
INSERT INTO `time_zone` VALUES (136, '(UTC -4) NAEDT – North American Eastern Daylight Time ');
INSERT INTO `time_zone` VALUES (137, '(UTC -4) HAE – Heure Avancée de l\'Est (French)');
INSERT INTO `time_zone` VALUES (138, '(UTC -4) EDT – Tiempo de verano del Este (Spanish)');
INSERT INTO `time_zone` VALUES (139, '(UTC +3) Eastern European Summer Time ');
INSERT INTO `time_zone` VALUES (140, '(UTC +3) EEDT – Eastern European Daylight Time ');
INSERT INTO `time_zone` VALUES (141, '(UTC +3) OESZ – Osteuropäische Sommerzeit (German)');
INSERT INTO `time_zone` VALUES (142, '(UTC +2) Eastern European Time ');
INSERT INTO `time_zone` VALUES (143, '(UTC +2) OEZ – Osteuropäische Zeit (German)');
INSERT INTO `time_zone` VALUES (145, '(UTC +0) Eastern Greenland Summer Time ');
INSERT INTO `time_zone` VALUES (146, '(UTC +0) EGST – East Greenland Summer Time');
INSERT INTO `time_zone` VALUES (147, '(UTC -1) East Greenland Time ');
INSERT INTO `time_zone` VALUES (148, '(UTC -1) EGT – Eastern Greenland Time');
INSERT INTO `time_zone` VALUES (149, '(UTC -5) Eastern Standard Time ');
INSERT INTO `time_zone` VALUES (150, '(UTC -5) ET – Eastern Time ');
INSERT INTO `time_zone` VALUES (151, '(UTC -5) NAEST – North American Eastern Standard Time ');
INSERT INTO `time_zone` VALUES (152, '(UTC -5) ET – Tiempo del Este (Spanish)');
INSERT INTO `time_zone` VALUES (153, '(UTC -5) HNE – Heure Normale de l\'Est (French)');
INSERT INTO `time_zone` VALUES (154, '(UTC -5:00 / -4:00) Eastern Time');
INSERT INTO `time_zone` VALUES (155, '(UTC -5:00 / -4:00) ');
INSERT INTO `time_zone` VALUES (156, '(UTC +6) Foxtrot Time Zone');
INSERT INTO `time_zone` VALUES (157, '(UTC +3) Further-Eastern European Time');
INSERT INTO `time_zone` VALUES (158, '(UTC +13) Fiji Summer Time ');
INSERT INTO `time_zone` VALUES (159, '(UTC +13) FJDT – Fiji Daylight Time');
INSERT INTO `time_zone` VALUES (160, '(UTC +12) Fiji Time');
INSERT INTO `time_zone` VALUES (161, '(UTC -3) Falkland Islands Summer Time ');
INSERT INTO `time_zone` VALUES (162, '(UTC -3) FKDT – Falkland Island Daylight Time');
INSERT INTO `time_zone` VALUES (163, '(UTC -4) Falkland Island Time ');
INSERT INTO `time_zone` VALUES (164, '(UTC -4) FKST – Falkland Island Standard Time');
INSERT INTO `time_zone` VALUES (165, '(UTC -2) Fernando de Noronha Time');
INSERT INTO `time_zone` VALUES (166, '(UTC +7) Golf Time Zone');
INSERT INTO `time_zone` VALUES (167, '(UTC -6) Galapagos Time');
INSERT INTO `time_zone` VALUES (168, '(UTC -9) Gambier Time ');
INSERT INTO `time_zone` VALUES (169, '(UTC -9) GAMT – Gambier Islands Time');
INSERT INTO `time_zone` VALUES (170, '(UTC +4) Georgia Standard Time');
INSERT INTO `time_zone` VALUES (171, '(UTC -3) French Guiana Time');
INSERT INTO `time_zone` VALUES (172, '(UTC +12) Gilbert Island Time');
INSERT INTO `time_zone` VALUES (173, '(UTC +0) Greenwich Mean Time ');
INSERT INTO `time_zone` VALUES (174, '(UTC +0) UTC – Coordinated Universal Time');
INSERT INTO `time_zone` VALUES (175, '(UTC +0) GT – Greenwich Time');
INSERT INTO `time_zone` VALUES (177, '(UTC +4) Gulf Standard Time');
INSERT INTO `time_zone` VALUES (178, '(UTC -2) South Georgia Time');
INSERT INTO `time_zone` VALUES (179, '(UTC -4) Guyana Time');
INSERT INTO `time_zone` VALUES (180, '(UTC +8) Hotel Time Zone');
INSERT INTO `time_zone` VALUES (181, '(UTC -9) Hawaii-Aleutian Daylight Time ');
INSERT INTO `time_zone` VALUES (182, '(UTC -9) HADT – Hawaii Daylight Time');
INSERT INTO `time_zone` VALUES (183, '(UTC +8) Hong Kong Time');
INSERT INTO `time_zone` VALUES (184, '(UTC +8) Hovd Summer Time ');
INSERT INTO `time_zone` VALUES (185, '(UTC +8) HOVDT – Hovd Daylight Time');
INSERT INTO `time_zone` VALUES (186, '(UTC +8) HOVDST – Hovd Daylight Saving Time');
INSERT INTO `time_zone` VALUES (187, '(UTC +7) Hovd Time');
INSERT INTO `time_zone` VALUES (188, '(UTC -10) Hawaii Standard Time ');
INSERT INTO `time_zone` VALUES (189, '(UTC -10) HAST – Hawaii-Aleutian Standard Time');
INSERT INTO `time_zone` VALUES (190, '(UTC +9) India Time Zone');
INSERT INTO `time_zone` VALUES (191, '(UTC +7) Indochina Time');
INSERT INTO `time_zone` VALUES (192, '(UTC +3) Israel Daylight Time');
INSERT INTO `time_zone` VALUES (193, '(UTC +6) Indian Chagos Time');
INSERT INTO `time_zone` VALUES (194, '(UTC +4:30) Iran Daylight Time ');
INSERT INTO `time_zone` VALUES (195, '(UTC +4:30) IRST – Iran Summer Time');
INSERT INTO `time_zone` VALUES (196, '(UTC +4:30) IDT – Iran Daylight Time');
INSERT INTO `time_zone` VALUES (197, '(UTC +9) Irkutsk Summer Time');
INSERT INTO `time_zone` VALUES (198, '(UTC +8) Irkutsk Time');
INSERT INTO `time_zone` VALUES (199, '(UTC +3:30) Iran Standard Time ');
INSERT INTO `time_zone` VALUES (200, '(UTC +3:30) IT – Iran Time');
INSERT INTO `time_zone` VALUES (201, '(UTC +5:30) India Standard Time ');
INSERT INTO `time_zone` VALUES (202, '(UTC +5:30) IT – India Time');
INSERT INTO `time_zone` VALUES (203, '(UTC +5:30) IST – Indian Standard Time');
INSERT INTO `time_zone` VALUES (204, '(UTC +1) Irish Standard Time ');
INSERT INTO `time_zone` VALUES (205, '(UTC +1) IST – Irish Summer Time');
INSERT INTO `time_zone` VALUES (206, '(UTC +2) Israel Standard Time');
INSERT INTO `time_zone` VALUES (207, '(UTC +9) Japan Standard Time');
INSERT INTO `time_zone` VALUES (208, '(UTC +10) Kilo Time Zone');
INSERT INTO `time_zone` VALUES (209, '(UTC +6) Kyrgyzstan Time');
INSERT INTO `time_zone` VALUES (210, '(UTC +11) Kosrae Time');
INSERT INTO `time_zone` VALUES (211, '(UTC +8) Krasnoyarsk Summer Time');
INSERT INTO `time_zone` VALUES (212, '(UTC +7) Krasnoyarsk Time');
INSERT INTO `time_zone` VALUES (213, '(UTC +9) Korea Standard Time ');
INSERT INTO `time_zone` VALUES (214, '(UTC +9) KST – Korean Standard Time');
INSERT INTO `time_zone` VALUES (215, '(UTC +9) KT – Korea Time');
INSERT INTO `time_zone` VALUES (216, '(UTC +4) Kuybyshev Time ');
INSERT INTO `time_zone` VALUES (217, '(UTC +4) SAMST – Samara Summer Time');
INSERT INTO `time_zone` VALUES (218, '(UTC +11) Lima Time Zone');
INSERT INTO `time_zone` VALUES (219, '(UTC +11) Lord Howe Daylight Time');
INSERT INTO `time_zone` VALUES (220, '(UTC +10:30) Lord Howe Standard Time');
INSERT INTO `time_zone` VALUES (221, '(UTC +14) Line Islands Time');
INSERT INTO `time_zone` VALUES (222, '(UTC +12) Mike Time Zone');
INSERT INTO `time_zone` VALUES (223, '(UTC +12) Magadan Summer Time ');
INSERT INTO `time_zone` VALUES (224, '(UTC +12) MAGST – Magadan Island Summer Time');
INSERT INTO `time_zone` VALUES (225, '(UTC +11) Magadan Time ');
INSERT INTO `time_zone` VALUES (226, '(UTC +11) MAGT – Magadan Island Time');
INSERT INTO `time_zone` VALUES (227, '(UTC -9:30) Marquesas Time');
INSERT INTO `time_zone` VALUES (228, '(UTC +5) Mawson Time');
INSERT INTO `time_zone` VALUES (229, '(UTC -6) Mountain Daylight Time ');
INSERT INTO `time_zone` VALUES (230, '(UTC -6) MDST – Mountain Daylight Saving Time');
INSERT INTO `time_zone` VALUES (231, '(UTC -6) NAMDT – North American Mountain Daylight Time ');
INSERT INTO `time_zone` VALUES (232, '(UTC -6) HAR – Heure Avancée des Rocheuses (French)');
INSERT INTO `time_zone` VALUES (233, '(UTC +12) Marshall Islands Time');
INSERT INTO `time_zone` VALUES (234, '(UTC +6:30) Myanmar Time');
INSERT INTO `time_zone` VALUES (235, '(UTC +4) Moscow Daylight Time ');
INSERT INTO `time_zone` VALUES (236, '(UTC +4) Moscow Summer Time');
INSERT INTO `time_zone` VALUES (237, '(UTC +3) Moscow Standard Time ');
INSERT INTO `time_zone` VALUES (238, '(UTC +3) MCK – Moscow Time');
INSERT INTO `time_zone` VALUES (239, '(UTC -7) Mountain Standard Time ');
INSERT INTO `time_zone` VALUES (240, '(UTC -7) MT – Mountain Time');
INSERT INTO `time_zone` VALUES (241, '(UTC -7) NAMST – North American Mountain Standard Time ');
INSERT INTO `time_zone` VALUES (242, '(UTC -7) HNR – Heure Normale des Rocheuses (French)');
INSERT INTO `time_zone` VALUES (243, '(UTC -7:00 / -6:00) Mountain Time');
INSERT INTO `time_zone` VALUES (244, '(UTC +4) Mauritius Time');
INSERT INTO `time_zone` VALUES (245, '(UTC +5) Maldives Time');
INSERT INTO `time_zone` VALUES (246, '(UTC +8) Malaysia Time ');
INSERT INTO `time_zone` VALUES (247, '(UTC +8) MST – Malaysian Standard Time');
INSERT INTO `time_zone` VALUES (248, '(UTC -1) November Time Zone');
INSERT INTO `time_zone` VALUES (249, '(UTC +11) New Caledonia Time');
INSERT INTO `time_zone` VALUES (250, '(UTC -2:30) Newfoundland Daylight Time ');
INSERT INTO `time_zone` VALUES (251, '(UTC -2:30) HAT – Heure Avancée de Terre-Neuve (French)');
INSERT INTO `time_zone` VALUES (252, '(UTC +11) Norfolk Time ');
INSERT INTO `time_zone` VALUES (253, '(UTC +11) NFT – Norfolk Island Time');
INSERT INTO `time_zone` VALUES (254, '(UTC +7) Novosibirsk Summer Time ');
INSERT INTO `time_zone` VALUES (255, '(UTC +7) OMSST – Omsk Summer Time');
INSERT INTO `time_zone` VALUES (256, '(UTC +7) Novosibirsk Time ');
INSERT INTO `time_zone` VALUES (257, '(UTC +7) OMST – Omsk Standard Time');
INSERT INTO `time_zone` VALUES (258, '(UTC +5:45) Nepal Time');
INSERT INTO `time_zone` VALUES (259, '(UTC +12) Nauru Time');
INSERT INTO `time_zone` VALUES (260, '(UTC -3:30) Newfoundland Standard Time ');
INSERT INTO `time_zone` VALUES (261, '(UTC -3:30) HNT – Heure Normale de Terre-Neuve (French)');
INSERT INTO `time_zone` VALUES (262, '(UTC -11) Niue Time');
INSERT INTO `time_zone` VALUES (263, '(UTC +13) New Zealand Daylight Time');
INSERT INTO `time_zone` VALUES (265, '(UTC +12) New Zealand Standard Time');
INSERT INTO `time_zone` VALUES (267, '(UTC -2) Oscar Time Zone');
INSERT INTO `time_zone` VALUES (268, '(UTC +7) Omsk Summer Time ');
INSERT INTO `time_zone` VALUES (269, '(UTC +7) NOVST – Novosibirsk Summer Time');
INSERT INTO `time_zone` VALUES (270, '(UTC +6) Omsk Standard Time ');
INSERT INTO `time_zone` VALUES (271, '(UTC +6) OMST – Omsk Time');
INSERT INTO `time_zone` VALUES (272, '(UTC +6) NOVT – Novosibirsk Time');
INSERT INTO `time_zone` VALUES (273, '(UTC +5) Oral Time');
INSERT INTO `time_zone` VALUES (274, '(UTC -3) Papa Time Zone');
INSERT INTO `time_zone` VALUES (275, '(UTC -7) Pacific Daylight Time ');
INSERT INTO `time_zone` VALUES (276, '(UTC -7) PDST – Pacific Daylight Saving Time');
INSERT INTO `time_zone` VALUES (277, '(UTC -7) NAPDT – North American Pacific Daylight Time ');
INSERT INTO `time_zone` VALUES (278, '(UTC -7) HAP – Heure Avancée du Pacifique (French)');
INSERT INTO `time_zone` VALUES (279, '(UTC -5) Peru Time');
INSERT INTO `time_zone` VALUES (280, '(UTC +12) Kamchatka Summer Time');
INSERT INTO `time_zone` VALUES (281, '(UTC +12) Kamchatka Time ');
INSERT INTO `time_zone` VALUES (282, '(UTC +12) PETT – Petropavlovsk-Kamchatski Time');
INSERT INTO `time_zone` VALUES (283, '(UTC +10) Papua New Guinea Time');
INSERT INTO `time_zone` VALUES (284, '(UTC +13) Phoenix Island Time');
INSERT INTO `time_zone` VALUES (285, '(UTC +8) Philippine Time ');
INSERT INTO `time_zone` VALUES (286, '(UTC +8) PST – Philippine Standard Time');
INSERT INTO `time_zone` VALUES (287, '(UTC +5) Pakistan Standard Time ');
INSERT INTO `time_zone` VALUES (288, '(UTC +5) PKT – Pakistan Time');
INSERT INTO `time_zone` VALUES (289, '(UTC -2) Pierre & Miquelon Daylight Time');
INSERT INTO `time_zone` VALUES (290, '(UTC -3) Pierre & Miquelon Standard Time');
INSERT INTO `time_zone` VALUES (291, '(UTC +11) Pohnpei Standard Time');
INSERT INTO `time_zone` VALUES (292, '(UTC -8) Pacific Standard Time ');
INSERT INTO `time_zone` VALUES (293, '(UTC -8) PT – Pacific Time');
INSERT INTO `time_zone` VALUES (294, '(UTC -8) NAPST – North American Pacific Standard Time ');
INSERT INTO `time_zone` VALUES (295, '(UTC -8) PT – Tiempo del Pacífico (Spanish)');
INSERT INTO `time_zone` VALUES (296, '(UTC -8) HNP – Heure Normale du Pacifique (French)');
INSERT INTO `time_zone` VALUES (297, '(UTC -8) Pitcairn Standard Time');
INSERT INTO `time_zone` VALUES (298, '(UTC -8:00 / -7:00) Pacific Time');
INSERT INTO `time_zone` VALUES (299, '(UTC +9) Palau Time');
INSERT INTO `time_zone` VALUES (300, '(UTC -3) Paraguay Summer Time');
INSERT INTO `time_zone` VALUES (301, '(UTC -4) Paraguay Time');
INSERT INTO `time_zone` VALUES (302, '(UTC +8:30) Pyongyang Time ');
INSERT INTO `time_zone` VALUES (303, '(UTC +8:30) PYST – Pyongyang Standard Time');
INSERT INTO `time_zone` VALUES (304, '(UTC -4) Quebec Time Zone');
INSERT INTO `time_zone` VALUES (305, '(UTC +6) Qyzylorda Time');
INSERT INTO `time_zone` VALUES (306, '(UTC -5) Romeo Time Zone');
INSERT INTO `time_zone` VALUES (307, '(UTC +4) Reunion Time');
INSERT INTO `time_zone` VALUES (308, '(UTC -3) Rothera Time');
INSERT INTO `time_zone` VALUES (309, '(UTC -6) Sierra Time Zone');
INSERT INTO `time_zone` VALUES (310, '(UTC +11) Sakhalin Time');
INSERT INTO `time_zone` VALUES (311, '(UTC +4) Samara Time ');
INSERT INTO `time_zone` VALUES (312, '(UTC +4) SAMT – Samara Standard Time');
INSERT INTO `time_zone` VALUES (313, '(UTC +2) South Africa Standard Time ');
INSERT INTO `time_zone` VALUES (314, '(UTC +2) SAST – South African Standard Time');
INSERT INTO `time_zone` VALUES (315, '(UTC +11) Solomon Islands Time ');
INSERT INTO `time_zone` VALUES (316, '(UTC +11) SBT – Solomon Island Time');
INSERT INTO `time_zone` VALUES (317, '(UTC +4) Seychelles Time');
INSERT INTO `time_zone` VALUES (318, '(UTC +8) Singapore Time ');
INSERT INTO `time_zone` VALUES (319, '(UTC +8) SST – Singapore Standard Time');
INSERT INTO `time_zone` VALUES (320, '(UTC +11) Srednekolymsk Time');
INSERT INTO `time_zone` VALUES (321, '(UTC -3) Suriname Time');
INSERT INTO `time_zone` VALUES (322, '(UTC -11) Samoa Standard Time');
INSERT INTO `time_zone` VALUES (323, '(UTC +3) Syowa Time');
INSERT INTO `time_zone` VALUES (324, '(UTC -7) Tango Time Zone');
INSERT INTO `time_zone` VALUES (325, '(UTC -10) Tahiti Time');
INSERT INTO `time_zone` VALUES (326, '(UTC +5) French Southern and Antarctic Time ');
INSERT INTO `time_zone` VALUES (327, '(UTC +5) KIT – Kerguelen (Islands) Time');
INSERT INTO `time_zone` VALUES (328, '(UTC +5) Tajikistan Time');
INSERT INTO `time_zone` VALUES (329, '(UTC +13) Tokelau Time');
INSERT INTO `time_zone` VALUES (330, '(UTC +9) East Timor Time');
INSERT INTO `time_zone` VALUES (331, '(UTC +5) Turkmenistan Time');
INSERT INTO `time_zone` VALUES (332, '(UTC +14) Tonga Summer Time');
INSERT INTO `time_zone` VALUES (333, '(UTC +13) Tonga Time');
INSERT INTO `time_zone` VALUES (334, '(UTC +3) Turkey Time');
INSERT INTO `time_zone` VALUES (336, '(UTC +12) Tuvalu Time');
INSERT INTO `time_zone` VALUES (337, '(UTC -8) Uniform Time Zone');
INSERT INTO `time_zone` VALUES (338, '(UTC +9) Ulaanbaatar Summer Time ');
INSERT INTO `time_zone` VALUES (339, '(UTC +9) ULAST – Ulan Bator Summer Time');
INSERT INTO `time_zone` VALUES (340, '(UTC +8) Ulaanbaatar Time ');
INSERT INTO `time_zone` VALUES (341, '(UTC +8) ULAT – Ulan Bator Time');
INSERT INTO `time_zone` VALUES (342, '(UTC) Coordinated Universal Time');
INSERT INTO `time_zone` VALUES (343, '(UTC -2) Uruguay Summer Time');
INSERT INTO `time_zone` VALUES (344, '(UTC -3) Uruguay Time');
INSERT INTO `time_zone` VALUES (345, '(UTC +5) Uzbekistan Time');
INSERT INTO `time_zone` VALUES (346, '(UTC -9) Victor Time Zone');
INSERT INTO `time_zone` VALUES (347, '(UTC -4) Venezuelan Standard Time ');
INSERT INTO `time_zone` VALUES (348, '(UTC -4) HLV – Hora Legal de Venezuela (Spanish)');
INSERT INTO `time_zone` VALUES (349, '(UTC +11) Vladivostok Summer Time');
INSERT INTO `time_zone` VALUES (350, '(UTC +10) Vladivostok Time');
INSERT INTO `time_zone` VALUES (351, '(UTC +6) Vostok Time');
INSERT INTO `time_zone` VALUES (352, '(UTC +11) Vanuatu Time ');
INSERT INTO `time_zone` VALUES (353, '(UTC +11) EFATE – Efate Time');
INSERT INTO `time_zone` VALUES (354, '(UTC -10) Whiskey Time Zone');
INSERT INTO `time_zone` VALUES (355, '(UTC +12) Wake Time');
INSERT INTO `time_zone` VALUES (356, '(UTC -3) Western Argentine Summer Time');
INSERT INTO `time_zone` VALUES (357, '(UTC +2) West Africa Summer Time');
INSERT INTO `time_zone` VALUES (358, '(UTC +1) West Africa Time');
INSERT INTO `time_zone` VALUES (359, '(UTC +1) Western European Summer Time ');
INSERT INTO `time_zone` VALUES (360, '(UTC +1) WEDT – Western European Daylight Time ');
INSERT INTO `time_zone` VALUES (361, '(UTC +1) WESZ – Westeuropäische Sommerzeit (German)');
INSERT INTO `time_zone` VALUES (362, '(UTC +0) Western European Time ');
INSERT INTO `time_zone` VALUES (363, '(UTC +0) GMT – Greenwich Mean Time ');
INSERT INTO `time_zone` VALUES (364, '(UTC +0) WEZ – Westeuropäische Zeit (German)');
INSERT INTO `time_zone` VALUES (365, '(UTC +12) Wallis and Futuna Time');
INSERT INTO `time_zone` VALUES (366, '(UTC -2) Western Greenland Summer Time ');
INSERT INTO `time_zone` VALUES (367, '(UTC -2) WGST – West Greenland Summer Time');
INSERT INTO `time_zone` VALUES (368, '(UTC -3) West Greenland Time ');
INSERT INTO `time_zone` VALUES (369, '(UTC -3) WGT – Western Greenland Time');
INSERT INTO `time_zone` VALUES (370, '(UTC +7) Western Indonesian Time ');
INSERT INTO `time_zone` VALUES (371, '(UTC +7) WIB – Waktu Indonesia Barat');
INSERT INTO `time_zone` VALUES (372, '(UTC +9) Eastern Indonesian Time ');
INSERT INTO `time_zone` VALUES (373, '(UTC +9) WIT – Waktu Indonesia Timur');
INSERT INTO `time_zone` VALUES (374, '(UTC +8) Central Indonesian Time ');
INSERT INTO `time_zone` VALUES (375, '(UTC +8) WITA – Waktu Indonesia Tengah');
INSERT INTO `time_zone` VALUES (376, '(UTC +14) West Samoa Time ');
INSERT INTO `time_zone` VALUES (377, '(UTC +14) ST – Samoa Time');
INSERT INTO `time_zone` VALUES (378, '(UTC +1) Western Sahara Summer Time');
INSERT INTO `time_zone` VALUES (379, '(UTC +0) Western Sahara Standard Time ');
INSERT INTO `time_zone` VALUES (380, '(UTC +0) WT – Western Sahara Time');
INSERT INTO `time_zone` VALUES (381, '(UTC -11) X-ray Time Zone');
INSERT INTO `time_zone` VALUES (382, '(UTC -12) Yankee Time Zone');
INSERT INTO `time_zone` VALUES (383, '(UTC +10) Yakutsk Summer Time');
INSERT INTO `time_zone` VALUES (384, '(UTC +9) Yakutsk Time');
INSERT INTO `time_zone` VALUES (385, '(UTC +10) Yap Time');
INSERT INTO `time_zone` VALUES (386, '(UTC +6) Yekaterinburg Summer Time');
INSERT INTO `time_zone` VALUES (387, '(UTC +5) Yekaterinburg Time');
INSERT INTO `time_zone` VALUES (388, '(UTC +0) Zulu Time Zone');

SET FOREIGN_KEY_CHECKS = 1;
